---
#
# edX Configuration
#
# github:     https://github.com/iitbmooc/bharatmooc-configuration
# wiki:       https://github.com/iitbmooc/bharatmooc-configuration/wiki
# code style: https://github.com/iitbmooc/bharatmooc-configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/iitbmooc/bharatmooc-configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role edx_service
# 

#
# vars are namespace with the module name.
#
edx_service_role_name: edx_service

#
# OS packages
#

edx_service_debian_pkgs: []

edx_service_redhat_pkgs: []
